// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTOFKOSPpa7ViHE77FUxxunsxp3C5dHMA',
    appId: '1:216465609942:web:d29426d938fb603dbe2577',
    messagingSenderId: '216465609942',
    projectId: 'mobile-banking-69073',
    authDomain: 'mobile-banking-69073.firebaseapp.com',
    storageBucket: 'mobile-banking-69073.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBift9KG_SdPo4wGaJsoH4yULPYkhfWWDo',
    appId: '1:216465609942:android:228efdc45fbbde64be2577',
    messagingSenderId: '216465609942',
    projectId: 'mobile-banking-69073',
    storageBucket: 'mobile-banking-69073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PsZ0KJqUbmMUZm_rvqxCNiI2pLst3es',
    appId: '1:216465609942:ios:6e18ba4e2c75399fbe2577',
    messagingSenderId: '216465609942',
    projectId: 'mobile-banking-69073',
    storageBucket: 'mobile-banking-69073.appspot.com',
    iosClientId: '216465609942-vvkiv9bj99ofjn4v8mjpi4ggcd85tbtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileBanking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PsZ0KJqUbmMUZm_rvqxCNiI2pLst3es',
    appId: '1:216465609942:ios:6e18ba4e2c75399fbe2577',
    messagingSenderId: '216465609942',
    projectId: 'mobile-banking-69073',
    storageBucket: 'mobile-banking-69073.appspot.com',
    iosClientId: '216465609942-vvkiv9bj99ofjn4v8mjpi4ggcd85tbtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileBanking',
  );
}
